## For the pima Indians dataset reduce the number of columns to 3 using PCA and develop an ML model using any one ML algorithm

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [7]:
path = "https://raw.githubusercontent.com/rohitgupta29/Datasets/master/Assignments/pima%20Indians%20Diabetes%20Dataset.csv"

df = pd.read_csv(path)

In [8]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [9]:
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix

X=df.iloc[:,:8]
y = df.iloc[:,8]

pca = PCA(3)

X_transformed = pca.fit_transform(X)

print(X.shape)

np. set_printoptions(suppress=True)
print(X_transformed.shape)
print(X_transformed)







(768, 8)
(768, 3)
[[-75.71465491 -35.95078264  -7.26078895]
 [-82.3582676   28.90821322  -5.49667139]
 [-74.63064344 -67.90649647  19.46180812]
 ...
 [ 32.11319827   3.3766648   -1.58786446]
 [-80.21449431 -14.18601977  12.3512639 ]
 [-81.30814972  21.62149606  -8.15276833]]


In [11]:
from sklearn.tree import DecisionTreeClassifier

from sklearn.pipeline import Pipeline

pipe = Pipeline([('pca', PCA(3)),
                 ('tree', DecisionTreeClassifier())])

pipe.fit(X, y)

p=pipe.predict(X)
print(confusion_matrix(y,p))


[[500   0]
 [  0 268]]
